title: "Sean Dewar"
logo: "/img/me-circle-border.png"
description: "Sean Dewar's Personal Website"
author: "Sean Dewar"

url: "https://seandewar.github.io"
baseurl: ""

google_analytics: "UA-148899653-1"
timezone: "Europe/London"
excerpt_separator: "<!--more-->"
