title: "Sean Dewar"
logo: "/img/me-circle-border.png"
author: "Sean Dewar"
description: >-
  Sean Dewar is a British Computer Science graduate with 1st-class honours who
  has been programming since childhood, working on many personal and
  open-source projects over the years.

url: "https://seandewar.github.io"
baseurl: ""

google_analytics: "UA-148899653-1"
timezone: "Europe/London"
excerpt_separator: "<!--more-->"
