title: "Sean Dewar"
logo: "/img/me-circle-border.png"
description: "Sean Dewar's personal GitHub pages site"
author: "Sean Dewar"

baseurl: ""
url: "https://seandewar.github.io"

timezone: "Europe/London"
google_analytics: "UA-148899653-1"
